# Generated by Django 5.2.1 on 2025-07-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopeapp', '0006_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
